services:
  - type: web
    name: ai-event-finder-web
    env: static
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true

    buildCommand: npm ci && npm run build
    staticPublishPath: dist

    envVars:
      - key: VITE_API_BASE_URL
        value: https://ai-event-finder.onrender.com
      - key: NODE_VERSION
        value: 20

    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
